## <f67r1.S> {}
# Labels in circle sectors
# Last edited on 1998-12-08 11:00:52 by stolfi
# clockwise, starting from the North
#
<f67r1.S.1;H>      otaldy=
<f67r1.S.1;C>      otaldy=
<f67r1.S.1;V>      otaldy=
#
<f67r1.S.2;H>      otoky=
<f67r1.S.2;C>      otoky=
<f67r1.S.2;V>      otoky=
#
<f67r1.S.3;H>      seeoa!r=
<f67r1.S.3;C>      seeya!r=
<f67r1.S.3;V>      seeaiir=
#
<f67r1.S.4;H>      yka!s.asa=
<f67r1.S.4;C>      yka!s.asy=
<f67r1.S.4;V>      ykees.ary=
#
<f67r1.S.5;H>      sosaiir=
<f67r1.S.5;C>      sosainr=
<f67r1.S.5;V>      sosaiir=
#
<f67r1.S.6;H>      oteey.dar=
<f67r1.S.6;C>      oteey.dar=
<f67r1.S.6;V>      oteey.dar=
#
<f67r1.S.7;H>      yto.daiir=
<f67r1.S.7;C>      yto!daiir=
<f67r1.S.7;V>      yto!daiir=
#
<f67r1.S.8;H>      sheosam=
<f67r1.S.8;C>      sheoraj=
<f67r1.S.8;V>      cheosam=
#
<f67r1.S.9;H>      ykeeody=
<f67r1.S.9;C>      ykeeody=
<f67r1.S.9;V>      ykeeody=
#
<f67r1.S.10;H>     okeol.sal=
<f67r1.S.10;C>     okeol.sal=
<f67r1.S.10;V>     okeol.sal=
#
<f67r1.S.11;H>     okeey.sar=
<f67r1.S.11;C>     okeey.sar=
<f67r1.S.11;V>     okeey.sar=
#
<f67r1.S.12;H>     dalary=
<f67r1.S.12;C>     dalary=
<f67r1.S.12;V>     dalary=
#
