## <f68v3.S> {}
# Radial text on spokes
# Last edited on 1998-12-08 23:55:24 by stolfi
#
# "U" transcription by J. Stolfi from scanned image
#
# SW short spoke
<f68v3.S.1;H>      ycheeo.ke{crease}y.qokal.okeeg=
<f68v3.S.1;C>      ych*!o.!d{crease}y.qokal.otch*=
<f68v3.S.1;U>      ycheeo.k*{crease}y.qokal.okchd=
# S long spoke 
#
<f68v3.S.2;H>      qokeody.okeey.chekchy.chckhy.okalody.chedy=
<f68v3.S.2;C>      qoteody.okeey.chekeey.chekey.okalody.chedy=
<f68v3.S.2;U>      qokeody.okeey.chekeey.chckhy.okalody.chedy=
# SE short spoke 
#
<f68v3.S.3;H>      shoekea!l.sheky.okolchey.okoldam=
<f68v3.S.3;C>      shoeke!!y.sheky.okolchey.okolmom=
<f68v3.S.3;U>      shoekeo*y.sheky.okolchey.okoldom=
# E long spoke 
#
<f68v3.S.4;H>      okeol.cheoda.qolkeey.ocheky.eeody.okchdy.oko.okos=
<f68v3.S.4;C>      okeol.cheody.qodkeey.ocheky.chody.otchdy.oto.oto*=
<f68v3.S.4;U>      okeol.cheody.qolkeey.ocheky.chody.otchdy.oko.okos=
# NE short spoke 
#
<f68v3.S.5;H>      r.al.chdail.schekol.okeody=
<f68v3.S.5;C>      *.al.chda!l.schekol.okeedy=
<f68v3.S.5;U>      r.al.chdail.schekol.okeody=
# N long spoke 
#
<f68v3.S.6;H>      ocheol.qoeey.keody.cheoky.okchy.chodo.dy.oteem=
<f68v3.S.6;C>      ocheol.qoeey.keody.cheoky.okchy.chod*.ty.otchm=
<f68v3.S.6;U>      ocheol.qoeey.keody.cheoky.okchy.chody.ty.otchm=
# NW short spoke 
#
<f68v3.S.7;H>      ydaiil.ol.chok.okchyd=
<f68v3.S.7;C>      ydainl.ol.chak.okchyd=
<f68v3.S.7;U>      ydaiil.ol.chak.okchyd=
# W long spoke 
#
<f68v3.S.8;H>      ochey.chekchy.dkeeeg.cheekey.te{crease}olkechey.saiir=
<f68v3.S.8;C>      echey.chekchy.dkeeel.che!key.ta{crease}!!kechey.daiin=
<f68v3.S.8;U>      ochey.chekchy.dkeeeg.cheekey.ta{crease}l!kechey.daiir=
#
