## <f71v.R2> {}
# Middle ring of text
# Last edited on 1998-11-27 17:55:32 by stolfi
#
# Transcription starting at 10 o'clock, going clockwise
#
<f71v.R2.1;H>      okol.sheeor.chal.oteeos.al.shsky.okalar.ar.okeo.dar.oty.oto.kaiin.chey.tol.otchr.chtos.cheor.shepchol.otor.sheo.shopcho.ar.aly.okeo.cheey.otal.al.shldy.otaly.
<f71v.R2.1;C>      okol.sheeor.chal.oteeos.al.sheky.okalar.ar.okeo.dar.oty.oto.kaiin.chey.tol.okchr.chtor.cheor.shepchol.otor.sheo.shopcho.ar.aly.okey.cheey.otal.al.sh*dy.otaly.
#
