## <f72r1.R2> {}
# Middle ring of text
# Last edited on 1998-12-28 00:24:15 by stolfi
#
# Transcribed clockwise from extra-wide gap at 09:00
# 
<f72r1.R2.1;H>     oteodar.ytey.otey.shetey.chokshor.okalal.otaiin.sheol.aiin.o!taiin.chetey.cheolor.oteo!teeody.otor.chokaiin.okaiin.al.alo.cheedy.oteor!ar.cheky.chokal.otas.al.o!qokar-{gap}
<f72r1.R2.1;U>     oteodar.ytey.otey.shetey.chokshor.okalal.otaiin.sheol!aiin.o,taiin.chetey.cheolor.oteo,te**dy.otor.chokaiin.okaiin.al,alo.cheedy.otear,ar.cheky.chotal.otar.al,o,qota*-{gap}
#
