## <f72v2.R2> {}
# Middle ring of text, starting from wider gap at 09:30
# Last edited on 1998-12-09 19:09:29 by stolfi
#
<f72v2.R2.1;H>     otees.ody.otey.otchos.sheot*.yteed.dchsaiin.shol.okches.air.am.shey.qokeodal.oteotey.oteoldy.oteal!chedy.chotal.al.okal.cheol.sar!aiin.cheokaidy.sa!ndy.otol.chskar.alteol.oltar.or-
<f72v2.R2.1;U>     otees!ody.otey.otchar.sheot*.yteeg.dchsaiin.shol.okeees.air.am.shey.qokeodal.oteotey.oteoldy.oteal,chedy.chotal,al.okal,cheol.sar,aiin.cheok*aly.sairdy.otol.chekar.alteol.oltar.ar-
#
