## <f83r.W> {}
# Labels on bottom left illustration - top labels
# Last edited on 1998-11-30 07:09:47 by stolfi
#
# "V" transcription by John Grove, posted 09-may-1998.
#
# nymph? - or left side of tube beside her
<f83r.W.1;H>       chtorol=
<f83r.W.1;V>       chtarol=
<f83r.W.1;U>       chtarol=
#
# nymph? - or right side of tube beside her
<f83r.W.2;H>       olsaiin=
<f83r.W.2;V>       olsaiin=
<f83r.W.2;U>       olsaiin=
#
