## <f83v.X> {}
# Labels on middle illustration
# Last edited on 1998-11-30 07:49:12 by stolfi
#
# "V" transcription by John Grove, posted 09-may-1998.
# Lines renumbered in the order they occur in Grove's listing. -JS
#
# nymph? - or large bulb beside her
<f83v.X.5;H>       ololary=
<f83v.X.5;V>       ololary=
<f83v.X.5;U>       ololary=
#
# nymph? - or end of large bulb beside her
<f83v.X.6;H>       okarchy=
<f83v.X.6;V>       okarchy=
<f83v.X.6;U>       okarchy=
#
