## <f100v.M> {}
# panel 100v, second row of plants
# Last edited on 1998-12-11 13:22:45 by stolfi 
#
# plant [2,1] - light inflorescene or berries, dark round leaves, light root
#
<f100v.M.1;H>      sol.eesos=
<f100v.M.1;K>      sol!eesos={was <f100v.35A;K>}
<f100v.M.1;V>      sol!eesos={was <f100v.B.5;V>}
#
# plant [2,2] - many small dark leaves, light roots
#
<f100v.M.2;H>      ykchochdy=
<f100v.M.2;K>      ykchochdy={was <f100v.36A;K>}
<f100v.M.2;V>      ykchochdy={was <f100v.B.6;V>}
#
# plant [2,3] - dark knobby leaves, dark root
#
<f100v.M.3;H>      ykchdy=
<f100v.M.3;K>      ykchdy={was <f100v.37A;K>}
<f100v.M.3;V>      ykchdy={was <f100v.B.7;V>}
#
# plant [2,4] - dark bushy leaves, slplayed roots
#
<f100v.M.4;H>      dchdy=
<f100v.M.4;K>      dchdy={was <f100v.38A;K>}
<f100v.M.4;V>      dchdy={was <f100v.B.8;V>}
#
# plant [2,5] - dark bushy leaves, light cauliflower, light stem
#
<f100v.M.5;H>      dalsy=
<f100v.M.5;K>      dalsy={was <f100v.39A;K>}
<f100v.M.5;V>      dalsy={was <f100v.B.9;V>}
#
