## <f100v.T> {}
# Panel 100v, top row of plants
# Last edited on 1998-12-10 09:01:26 by stolfi
# 
# plant [1,1] - dark leaves with white teeth, dark root
# 
<f100v.T.1;H>      tolchd=
<f100v.T.1;K>      tolchd={was <f100v.31A;K>}
<f100v.T.1;V>      tolchd={was <f100v.B.1;V>}
# 
# plant [1,2] - light flower, dark curled leaves, dark root
# 
<f100v.T.2;H>      chols=
<f100v.T.2;K>      chols={was <f100v.32A;K>}
<f100v.T.2;V>      chols={was <f100v.B.2;V>}
# 
# plant [1,3] - many dark leaves, dark roots
# 
<f100v.T.3;H>      opchor=
<f100v.T.3;K>      opchor={was <f100v.33A;K>}
<f100v.T.3;V>      opchor={was <f100v.B.3;V>}
# 
# plant [1,4] - dark leaves on right side of stem only
# 
<f100v.T.4;H>      rolsy=
<f100v.T.4;K>      solsy={was <f100v.34A;K>}
<f100v.T.4;V>      solsy={was <f100v.B.4;V>}
#
# intruding flower of plant [2,5]
#
