## <f68r1.X> {}
# Title inside top medallion (face in sun)
# Last edited on 1998-10-20 00:12:05 by stolfi
#
# "U" transcription by J. Stolfi from scanned image
# "V" transcription by John Grove.
#
<f68r1.X.1;H>      yky-
<f68r1.X.1;U>      yky-
<f68r1.X.1;V>      oty-
#
<f68r1.X.2;H>      dary-
<f68r1.X.2;U>      dary-
<f68r1.X.2;V>      dary-
#
<f68r1.X.3;H>      chkchykoly=
<f68r1.X.3;U>      chkchykoly=
<f68r1.X.3;V>      chkchykoly=
#
#
