## <f70r1.I> {}
# Circular lines - ring of text around central disk
# Last edited on 1998-11-24 04:32:20 by stolfi
#
# "U" transcription by J. Stolfi from scanned image.
#
# Transcription clockwise starting from the faint lines at 10:30
<f70r1.I.1;H>      otechg.tshey.ol.oteey.ched.ar.oteos.sheor.al!al.otar.ar!y.oteod!shey.keody.oteos.al.
<f70r1.I.1;U>      okeeed.tshsy.ol.oteey.ched,ar.oteos.cheor,al,al.otar,ar,y.oteod,chey.keody.oteos,al.
#
