## <f83r.Y> {}
# Bottom left illustration - labels on bottom structures
#
# "V" transcription by John Grove, posted 09-may-1998.
# Lines renumbered in the order they occur in Grove's listing. -JS
#
# flow? - spray, seeds?
<f83r.Y.6;H>       sarol!dal=
<f83r.Y.6;V>       saral!dal=
<f83r.Y.6;U>       sarol,dal=
#
# flow? - spray, seeds?
<f83r.Y.7;H>       darolsy=
<f83r.Y.7;V>       darolsy=
<f83r.Y.7;U>       darolsy=
#
