## <f101v2.T> {}
# centered title spanning f101v2 and f101v1
# Last edited on 1998-12-11 13:35:12 by stolfi
#
# "U" transcription by J. Stolfi from scanned image
# Joined with f101v1.T by J. Stolfi Oct/1998
#
<f101v2.T.9;H>     teol.cheol.ekchey!-{fold}****or.cheol.cthol**{blot}.cholaiin.chol.qkos=
<f101v2.T.9;F>     teol.cheol.ot.!***-{fold}***qor.cheol.!!!!!**{blot}.cholaiin.chol.qkar=
<f101v2.T.9;U>     teol.cheol.otch***-{fold}***!or.cheol.cthol**{blot}.cholaiin.chol.qkar=
#
