## <f39r.T> {}
# title under third paragraph (end of text).
# Last edited on 1998-12-07 06:51:08 by stolfi
#
# "U" transcription by J.Stolfi from an unidentified image.
#
# The part after the "-" is a bit lower than the rest.
<f39r.T.16;H>      oteol.cholkal-{\}qokal.dar.ykdy=
<f39r.T.16;C>      oteol.cholkal-{\}qokal.dar.ykdy=
<f39r.T.16;F>      oteol.cholkal-{\}qokal.dar.ykdy=
<f39r.T.16;U>      oteol.cholkal-{\}qokyl.dar.ykdy=
#
