## <f66r.W> {}
# panel f66r, caption above female figure
# Last edited on 1998-12-08 10:53:54 by stolfi
#
# "V" transcription by John Grove, entered by Stolfi
# "U" transcription by J.Stolfi from unidentified scan.
#
<f66r.W.1;H>       otcheo.!!!!!!chty.ykchs!che!g=
<f66r.W.1;C>       otcheo.daiin.chty.ynchs!cheim=
<f66r.W.1;V>       otcheo.daiin.chty.ykees.che!g=
<f66r.W.1;U>       otcheo.daiin.chty.ykees.che!g=
#
