## <f66r.M> {}
# panel f66r, letters/symbols along middle column
# Last edited on 1998-12-27 23:33:21 by stolfi
# 
# "U" transcription by J.Stolfi from unidentified scan.
#
# Weirdos
#
#   &172 = upside down lambda.
#   &195 = like an EVA <I> with an upturned serif at the right end.
#
<f66r.M.1;H>       y=
<f66r.M.1;C>       y=
<f66r.M.1;F>       y=
<f66r.M.1;U>       y=
#
<f66r.M.2;H>       o=
<f66r.M.2;C>       o=
<f66r.M.2;F>       o=
<f66r.M.2;U>       o=
#
<f66r.M.3;H>       s=
<f66r.M.3;C>       s=
<f66r.M.3;F>       s=
<f66r.M.3;U>       s=
#
<f66r.M.4;H>       sh=
<f66r.M.4;C>       sh=
<f66r.M.4;F>       sh=
<f66r.M.4;U>       sh=
#
<f66r.M.5;H>       y=
<f66r.M.5;C>       y=
<f66r.M.5;F>       y=
<f66r.M.5;U>       y=
#
<f66r.M.6;H>       d=
<f66r.M.6;C>       d=
<f66r.M.6;F>       d=
<f66r.M.6;U>       d=
#
<f66r.M.7;H>       o=
<f66r.M.7;C>       o=
<f66r.M.7;F>       o=
<f66r.M.7;U>       o=
#
<f66r.M.8;H>       f=
<f66r.M.8;C>       f=
<f66r.M.8;F>       p=
<f66r.M.8;U>       f=
#
<f66r.M.9;H>       *=
<f66r.M.9;C>       *=
<f66r.M.9;F>       o=
<f66r.M.9;U>       *=
#
<f66r.M.10;H>      x=
<f66r.M.10;C>      x=
<f66r.M.10;F>      x=
<f66r.M.10;U>      x=
#
<f66r.M.11;H>      air=
<f66r.M.11;C>      air=
<f66r.M.11;F>      air=
<f66r.M.11;U>      air=
#
<f66r.M.12;H>      d=
<f66r.M.12;C>      d=
<f66r.M.12;F>      d=
<f66r.M.12;U>      d=
#
<f66r.M.13;H>      sh=
<f66r.M.13;C>      sh=
<f66r.M.13;F>      sh=
<f66r.M.13;U>      sh=
#
<f66r.M.14;H>      y=
<f66r.M.14;C>      y=
<f66r.M.14;F>      y=
<f66r.M.14;U>      y=
#
<f66r.M.15;H>      f!!!!!!!!!!!!!!=
<f66r.M.15;C>      f!!!!!!!!!!!!!!=
<f66r.M.15;F>      f!!!!!!!!!!!!!!=
<f66r.M.15;U>      f{straight arm}=
#
<f66r.M.16;H>      f!!!!!!!!!!!!=
<f66r.M.16;C>      f!!!!!!!!!!!!=
<f66r.M.16;F>      f!!!!!!!!!!!!=
<f66r.M.16;U>      f{hooked arm}=
#
<f66r.M.17;H>      y=
<f66r.M.17;C>      y=
<f66r.M.17;F>      y=
<f66r.M.17;U>      y=
#
<f66r.M.18;H>      o=
<f66r.M.18;C>      o=
<f66r.M.18;F>      !=
<f66r.M.18;U>      o=
#
<f66r.M.19;H>      d=
<f66r.M.19;C>      d=
<f66r.M.19;F>      d=
<f66r.M.19;U>      d=
#
<f66r.M.20;H>      r=
<f66r.M.20;C>      s=
<f66r.M.20;F>      r=
<f66r.M.20;U>      r=
#
<f66r.M.21;H>      f=
<f66r.M.21;C>      t=
<f66r.M.21;F>      f=
<f66r.M.21;U>      f=
#
<f66r.M.22;H>      c=
<f66r.M.22;C>      c=
<f66r.M.22;F>      e=
<f66r.M.22;U>      c=
#
<f66r.M.23;H>      r{&172}=
<f66r.M.23;C>      *!!!!!!=
<f66r.M.23;F>      *!!!!!!=
<f66r.M.23;U>      r{&172}=
#
<f66r.M.24;H>      x=
<f66r.M.24;C>      x=
<f66r.M.24;F>      x=
<f66r.M.24;U>      x=
#
<f66r.M.25;H>      t=
<f66r.M.25;C>      t=
<f66r.M.25;F>      t=
<f66r.M.25;U>      t=
#
<f66r.M.26;H>      o=
<f66r.M.26;C>      o=
<f66r.M.26;F>      o=
<f66r.M.26;U>      o=
#
<f66r.M.27;H>      *{&195}=
<f66r.M.27;C>      *!!!!!!=
<f66r.M.27;F>      r!!!!!!=
<f66r.M.27;U>      *{&195}={or &172}
#
<f66r.M.28;H>      l=
<f66r.M.28;C>      l=
<f66r.M.28;F>      l=
<f66r.M.28;U>      l=
#
<f66r.M.29;H>      r=
<f66r.M.29;C>      r=
<f66r.M.29;F>      r=
<f66r.M.29;U>      r=
#
<f66r.M.30;H>      t=
<f66r.M.30;C>      t=
<f66r.M.30;F>      t=
<f66r.M.30;U>      t=
#
<f66r.M.31;H>      o=
<f66r.M.31;C>      o=
<f66r.M.31;F>      o=
<f66r.M.31;U>      o=
#
<f66r.M.32;H>      x=
<f66r.M.32;C>      x=
<f66r.M.32;F>      x=
<f66r.M.32;U>      x=
#
<f66r.M.33;H>      p=
<f66r.M.33;C>      p=
<f66r.M.33;F>      p=
<f66r.M.33;U>      p=
#
<f66r.M.34;H>      d=
<f66r.M.34;C>      d=
<f66r.M.34;F>      d=
<f66r.M.34;U>      d=
#
#
