## <f67v2.S> {}
# Labels next to central square
# Last edited on 1998-12-26 06:02:05 by stolfi
#
# "V" transcription by J. Grove
# "U" transcription by J. Stolfi from scanned image
#
# North side
#
<f67v2.S.1;H>      soaiin-{plant}dalam=
<f67v2.S.1;C>      soaiin-{plant}dolaj=
<f67v2.S.1;V>      soeiin-{plant}dalam=
<f67v2.S.1;U>      soaiin-{plant}dalam=
#
# South side
#
<f67v2.S.2;H>      sory-{plant}okoral=
<f67v2.S.2;C>      soly-{plant}okorad=
<f67v2.S.2;V>      sary-{plant}okoral=
<f67v2.S.2;U>      sary-{plant}okoral=
#
