## <f68r1.Y> {}
# Title around bottom medallion (face in moon)
# Last edited on 1998-12-08 11:37:25 by stolfi
#
# "U" transcription by J. Stolfi from scanned image
# "V" transcription by John Grove.
#
# The writing is awkward - letters tend to remain upright even at the
# ends, where the text is almost vertical.
#
<f68r1.Y.1;H>      oky.oka!dy.okardy.q*aear.oldy=
<f68r1.Y.1;U>      oky.okchdy.okardy.l**sar.olgy=
<f68r1.Y.1;V>      oky.okchdy.okardy.t*!sar.olgy={Grove's C1}
#
