## <f68r1.S> {}
# Labels on 29 stars
# Last edited on 1998-12-11 12:58:32 by stolfi
#
# "V" transcription by J. Grove
# "U" transcription by J. Stolfi from scanned image
#
<f68r1.S.1;H>      chocphy=
<f68r1.S.1;V>      chocfhy=
<f68r1.S.1;U>      chocfhy=
#
<f68r1.S.2;H>      cphocthy=
<f68r1.S.2;V>      cphocthy=
<f68r1.S.2;U>      cphocthy=
#
<f68r1.S.3;H>      dolchedy=
<f68r1.S.3;V>      dolchedy=
<f68r1.S.3;U>      dolchedy=
#
<f68r1.S.4;H>      ockhy=
<f68r1.S.4;V>      ockhy=
<f68r1.S.4;U>      ockhy=
#
<f68r1.S.5;H>      ocphy=
<f68r1.S.5;V>      ocphy=
<f68r1.S.5;U>      ocphy=
#
<f68r1.S.6;H>      octhey=
<f68r1.S.6;V>      octhey=
<f68r1.S.6;U>      octhey=
#
<f68r1.S.7;H>      otcheody=
<f68r1.S.7;V>      odcheody=
<f68r1.S.7;U>      otcheody=
#
<f68r1.S.8;H>      odchecthy=
<f68r1.S.8;V>      odchecthy=
<f68r1.S.8;U>      odchecthy=
#
<f68r1.S.9;H>      ofcheor=
<f68r1.S.9;V>      ofcheor=
<f68r1.S.9;U>      ofcheor=
#
<f68r1.S.10;H>     oiin!ar=
<f68r1.S.10;V>     oiin!ar=
<f68r1.S.10;U>     oiin,ar=
#
<f68r1.S.11;H>     okeor=
<f68r1.S.11;V>     okear=
<f68r1.S.11;U>     okear=
#
<f68r1.S.12;H>     okeeodal=
<f68r1.S.12;V>     okeeodal=
<f68r1.S.12;U>     okeeodal=
#
<f68r1.S.13;H>     okoaly=
<f68r1.S.13;V>     okoaly=
<f68r1.S.13;U>     okoaly=
#
<f68r1.S.14;H>     okoldy=
<f68r1.S.14;V>     okoldy=
<f68r1.S.14;U>     okoldy=
#
<f68r1.S.15;H>     okshor=
<f68r1.S.15;V>     okshor=
<f68r1.S.15;U>     okshor=
#
<f68r1.S.16;H>     olor=
<f68r1.S.16;V>     olor=
<f68r1.S.16;U>     olor=
#
<f68r1.S.17;H>     or!daiin=
<f68r1.S.17;V>     or.daiin=
<f68r1.S.17;U>     or,daiin=
#
<f68r1.S.18;H>     ytchody=
<f68r1.S.18;V>     otch!do=
<f68r1.S.18;U>     otch!do=
#
<f68r1.S.19;H>     otochedy=
<f68r1.S.19;V>     otochedy=
<f68r1.S.19;U>     otochedy=
#
<f68r1.S.20;H>     okodaly=
<f68r1.S.20;V>     otodaly=
<f68r1.S.20;U>     okodaly=
#
<f68r1.S.21;H>     otol=
<f68r1.S.21;V>     otol=
<f68r1.S.21;U>     otol=
#
<f68r1.S.22;H>     otor=
<f68r1.S.22;V>     otor=
<f68r1.S.22;U>     otor=
#
<f68r1.S.23;H>     otcsey=
<f68r1.S.23;V>     otshey=
<f68r1.S.23;U>     otshey=
#
<f68r1.S.24;H>     otydy=
<f68r1.S.24;V>     otydy=
<f68r1.S.24;U>     otydy=
#
<f68r1.S.25;H>     otykchs=
<f68r1.S.25;V>     otykchs=
<f68r1.S.25;U>     otykchs=
#
<f68r1.S.26;H>     otys=
<f68r1.S.26;V>     otys=
<f68r1.S.26;U>     otys=
#
# The two "t"s below are a single four-loop "t" with the right foot as the plume of "sh"
<f68r1.S.27;H>     toeeodcthy=
<f68r1.S.27;V>     toeeodc!hy=
<f68r1.S.27;U>     toeeods!hy=
#
<f68r1.S.28;H>     ykchdy=
<f68r1.S.28;V>     ykchdy=
<f68r1.S.28;U>     ykchdy=
#
<f68r1.S.29;H>     otcs!do=
<f68r1.S.29;V>     ytchody=
<f68r1.S.29;U>     ytchody=
#
