## <f68r2.S> {}
# Labels on 24 stars
# Last edited on 1998-12-08 11:41:28 by stolfi
#
# Read in row from left to right across the page, and from top
# to bottom (i.e. normal reading order)
#
# "R" transcription by Roe, 23 July 1996 from BL microfilm
# "U" transcription by J. Stolfi from scanned image
# "V" transcription by John Grove.
# 
<f68r2.S.0;H>      otolchcthy=
<f68r2.S.0;R>      otolch!tey=
<f68r2.S.0;V>      otolchc!hy={gallows lands on 2nd 'ch'}
<f68r2.S.0;U>      opolchs!hy={gallows lands on 'sh'}
#
# (unnamed star)
#
<f68r2.S.1;H>      cheo!rol=
<f68r2.S.1;R>      cheo!rol=
<f68r2.S.1;V>      cheo.rol=
<f68r2.S.1;U>      cheo,rol=
#
<f68r2.S.2;H>      odaiin=
<f68r2.S.2;R>      odaiir=
<f68r2.S.2;V>      odaiin=
<f68r2.S.2;U>      odaiin=
#
<f68r2.S.3;H>      ochory=
<f68r2.S.3;R>      ochory=
<f68r2.S.3;V>      ochary=
<f68r2.S.3;U>      ochory=
#
# (unnamed star)
#
<f68r2.S.4;H>      shdar=
<f68r2.S.4;R>      shdar=
<f68r2.S.4;V>      shdar=
<f68r2.S.4;U>      shdar=
#
# (unnamed star)
#
<f68r2.S.5;H>      dchol=
<f68r2.S.5;R>      dchol=
<f68r2.S.5;V>      dchol=
<f68r2.S.5;U>      dchol=
#
<f68r2.S.6;H>      todaraiil!y!!=
<f68r2.S.6;R>      eeodaraii*y!!=
<f68r2.S.6;V>      todaraiil!y!!=
<f68r2.S.6;U>      todaraiil{y?}=
#
<f68r2.S.7;H>      olcheesey=
<f68r2.S.7;R>      olcheeeey=
<f68r2.S.7;V>      olcheesey=
<f68r2.S.7;U>      olcheesey=
#
<f68r2.S.8;H>      okchor=
<f68r2.S.8;R>      okchor=
<f68r2.S.8;V>      okchor=
<f68r2.S.8;U>      okchor=
#
<f68r2.S.9;H>      oteool=
<f68r2.S.9;R>      oteo*l=
<f68r2.S.9;V>      otoa!l=
<f68r2.S.9;U>      oteo*l=
#
# (unnamed star)
#
<f68r2.S.10;H>     oydchy=
<f68r2.S.10;R>     oydchy=
<f68r2.S.10;V>     oydchy=
<f68r2.S.10;U>     oydchy=
#
# (unnamed star)
#
# (unnamed star)
#
<f68r2.S.11;H>     cholar=
<f68r2.S.11;R>     chodar=
<f68r2.S.11;V>     cholar=
<f68r2.S.11;U>     cholar=
#
# (unnamed star)
#
<f68r2.S.12;H>     okcheody=
<f68r2.S.12;R>     okeeeody=
<f68r2.S.12;V>     okeeeody=
<f68r2.S.12;U>     okeeeody=
#
# (unnamed star)
#
<f68r2.S.13;H>     dcheoldy=
<f68r2.S.13;R>     dcheoldy=
<f68r2.S.13;V>     dcheoldy=
<f68r2.S.13;U>     dcheoldy=
#
# (unnamed star)
#
<f68r2.S.14;H>     oteeeo!r=
<f68r2.S.14;R>     oteeeiir=
<f68r2.S.14;V>     oteeeo!r=
<f68r2.S.14;U>     oteeea!r=
#
# (unnamed star)
#
# (unnamed star)
#
<f68r2.S.15;H>     etocho=
<f68r2.S.15;R>     otoeeo=
<f68r2.S.15;V>     otoeeo=
<f68r2.S.15;U>     otoeeo=
#
<f68r2.S.16;H>     ofchsody=
<f68r2.S.16;R>     ofcheody=
<f68r2.S.16;V>     ofcheody=
<f68r2.S.16;U>     ofcheody=
#
<f68r2.S.17;H>     otcheodar=
<f68r2.S.17;R>     otcheodar=
<f68r2.S.17;V>     otcheodar=
<f68r2.S.17;U>     otcheodar=
#
<f68r2.S.18;H>     odai!r.chol=
<f68r2.S.18;R>     odiiir.chol={merged with <f68r2.S.19;R>}
<f68r2.S.18;V>     odai!r.chol={merged with <f68r2.S.19;V>}
<f68r2.S.18;U>     odai!r,chol=
#
# <f68r2.S.19;R>, <f68r2.S.19;V> deleted, see above
#
<f68r2.S.20;H>     opocphor=
<f68r2.S.20;R>     opocphor=
<f68r2.S.20;V>     opocphar=
<f68r2.S.20;U>     opocphor=
#
<f68r2.S.21;H>     otoshol=
<f68r2.S.21;R>     otoshos=
<f68r2.S.21;V>     otoshol=
<f68r2.S.21;U>     otoshol=
#
<f68r2.S.22;H>     chodar=
<f68r2.S.22;R>     chodar=
<f68r2.S.22;V>     chodar=
<f68r2.S.22;U>     chodar=
#
<f68r2.S.23;H>     shchy=
<f68r2.S.23;R>     shchy=
<f68r2.S.23;V>     shchy=
<f68r2.S.23;U>     sheey=
#
<f68r2.S.24;H>     okeechor=
<f68r2.S.24;R>     okeechor=
<f68r2.S.24;V>     okeechor=
<f68r2.S.24;U>     okeechor=
#
# (unnamed star)
#
#
