## <f68v2.S> {}
# Radial labels with stars
# Last edited on 1998-12-08 23:32:04 by stolfi
#
# "V" transcription by John Grove.
# "U" transcription by J. Stolfi from scanned image.
#
# The original line numbers were assigned by J.Stolfi 
# starting from 12:30; they were reassigned on Oct/1998
# to match the order of Grove's numbering, and to 
# interleave properly with the radial line numbers (unit "R")
#
# clockwise, starting at 10:30
#
# star at 10:30
<f68v2.S.1;H>      y!keeepol-{star}y!pchy=
<f68v2.S.1;C>      ilkeeepol-{star}yypchy=
<f68v2.S.1;U>      y!keeepol-{star}y!pchy=
<f68v2.S.1;V>      y!keeepol-{star}y!pchy={Grove's L1}
#
# star at 1:30
<f68v2.S.4;H>      otosey-{star}sa!!!ry!!=
<f68v2.S.4;C>      otosey-{star}sa!!!ry!!=
<f68v2.S.4;U>      otoshy-{star}sa!!!ry!!=
<f68v2.S.4;V>      otoshy-{star}*{&c'a}ry={Grove's L2}
#
# star at 4:30
<f68v2.S.7;H>      oteoys-{star}orasaly=
<f68v2.S.7;C>      oteoys-{star}oraraly=
<f68v2.S.7;U>      oteoys-{star}orasaly=
<f68v2.S.7;V>      oteods-{star}osaraly={Grove's L3}
#
# star at 7:30
<f68v2.S.10;H>     otchdy-{star}chetal=
<f68v2.S.10;C>     otchdy-{star}chetal=
<f68v2.S.10;U>     otchdy-{star}chetal=
<f68v2.S.10;V>     otchdy-{star}chetal={Grove's L4}
#
