## <f68v3.L> {}
# Central circle ("T-O map"), top half
# Last edited on 1998-12-26 06:19:15 by stolfi
#
# "V" transcription by John Grove.
# "U" transcription by J. Stolfi from scanned image.
#
# Top left quarter
#
<f68v3.L.1;H>      otodol=
<f68v3.L.1;C>      otodol=
<f68v3.L.1;V>      otodol=
<f68v3.L.1;U>      otodal=
#
# Top right quarter
#
<f68v3.L.2;H>      opcholdg=
<f68v3.L.2;C>      opeealdm=
<f68v3.L.2;V>      opchaldg=
<f68v3.L.2;U>      opchaldg=
#
