## <f69r.S> {}
# Inner ring of text
# Last edited on 1998-12-09 17:33:47 by stolfi
#
# "U" transcription by J. Stolfi from scanned image
# "V" transcription by John Grove
#
# Transcribed clockwise from wider gap at 10:00
#
<f69r.S.1;H>       oko!eese.dain!key.ochs.cheor.yteey.o!kcheo.dar.cho.okchos.al.aiin=
<f69r.S.1;U>       okcheesy.dain,key.oees.cheor.yteey.o,kee!o,dar.cho.okeeor.al.aiin=
<f69r.S.1;V>       okcheese.daii!key.oees.chear.yteey.o!keeeo!dar.cho.okchos.al.aiin=
#
