## <f72v3.R2> {}
# middle ring of text
# Last edited on 1998-12-09 19:24:09 by stolfi
#
# Transcribed clockwise from wider gap(?) at 08:45
#
<f72v3.R2.1;H>     !!!!!!!!!!shos.{fold}otchy.!**eody.cheokey.okeoekol.oteos.aiin.yal.eeedy.okeos.aly.shy.oka!y.okeeey.okeedal!y.cholairy.oke!!.chees!y.okeeol.chey.otey.aldy.chdy.del.ok*eoloky.oty.aiin.cheis.otoly{fold}.ok****.etoteear-
<f72v3.R2.1;U>     *t***.***.!***.{fold}***!!.**eeody.cheokeo.okeoekal.oteor,aiin.yol,eeedy.okeos,aly!shy.okeey.okeeey.okeedal,y.cholairy.okedy.chees,y.okeeol.chey.okey,aldy.chdy,dal.oksholoky.oty.aiin.cha!s.oteey{fold}.**!!!*.*t**!*.*-
#
