## <f73r.R2> {}
# middle ring of text
# Last edited on 1998-12-10 01:04:48 by stolfi
# 
# Transcribed clockwise from wider gap at 10:30
#
<f73r.R2.1;H>      oteey.dar.al.opaiin.olalaiin.sair.ar.chopchedy.chdar.orom.otor!eees.olteey.okees.otar.chey.oteas.oho!r.op!ar.chey.daiin.qoiheey.s!cheey.dal.cheesy.
<f73r.R2.1;U>      otchy.dar.yl.opaiin.olalaiin.r,aisam.chopchedy.chdar.oram.otar,eees.alteey.okchs.otar!chey.oteas,cho,r.opees,chey.daiin.qoche!y.s,cheey.dal,cha!ry.
#
