## <f73v.R2> {}
# middle ring of text
# Last edited on 1998-12-10 01:08:00 by stolfi
#
# Transcribed clockwise from extra-wide gap at 10:00
#
<f73v.R2.1;H>      oteotor.alshy.oteolain.chokeedam.otody.qoty.shedy.chdy.tchol.oteody.cheytey.choty.okey.dy.okecholy.otey.chodaiin.chey.okchdy.saly.ar.daly-{gap}
<f73v.R2.1;U>      oteotor.alshy.oteolain.choka!dam.otody.qoty,shedy.chdy.tchol!oteody.cheytey.choty.okey,dy.okecholy.otey.chodaiin.chey.okeedy.raly.ar.daly-{gap}
#
