## <f83v.Y> {}
# Labels on bottom right illustration
# Last edited on 1998-11-30 07:49:33 by stolfi
#
# "V" transcription by John Grove, posted 09-may-1998.
#
# nymph? - or bottom of tube below her
<f83v.Y.7;H>       okchdy=
<f83v.Y.7;V>       okaiin=
<f83v.Y.7;U>       okaiin=
#
# nymph? - or top of tube above her
<f83v.Y.8;H>       okaiin=
<f83v.Y.8;F>       okchdy=
<f83v.Y.8;V>       okchdy=
<f83v.Y.8;U>       okchdy=
#
